{
  config,
  pkgs,
  ...
}: {
  programs.home-manager.enable = true;

  # home = {
  #   username = "pancho";
  #   homeDirectory = "/home/pancho";
  #   stateVersion = "22.11";
  # };

  wayland.windowManager.hyprland = {
    enable = true;
    extraConfig = ''
      ########################################################################################
      AUTOGENERATED HYPR CONFIG.
      PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
      OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
      ########################################################################################

      #
      # Please note not all available settings / options are set here.
      # For a full list, see the wiki
      #

      # See https://wiki.hyprland.org/Configuring/Monitors/
      monitor=,preferred,auto,auto


      # See https://wiki.hyprland.org/Configuring/Keywords/ for more

      # Execute your favorite apps at launch
      # exec-once = waybar & hyprpaper & firefox

      # Source a file (multi-file configs)
      # source = ~/.config/hypr/myColors.conf

      # Some default env vars.
      env = XCURSOR_SIZE,24

      # For all categories, see https://wiki.hyprland.org/Configuring/Variables/
      input {
          kb_layout = us
          kb_variant =
          kb_model =
          kb_options =
          kb_rules =

          follow_mouse = 1

          touchpad {
              natural_scroll = no
          }

          sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
      }

      # https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs
      device:keychron-keychron-q8 {
          kb_model = pc105
          kb_layout = us,us
          kb_variant = altgr-intl,dvorak
          #kb_options = compose:sclk,grp:caps_toggle,grp_led:caps,shift:both_capslock
          kb_options = compose:sclk,grp:shifts_toggle
      }

      general {
          # See https://wiki.hyprland.org/Configuring/Variables/ for more

          gaps_in = 5
          gaps_out = 20
          border_size = 2
          col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
          col.inactive_border = rgba(595959aa)

          layout = dwindle
      }

      decoration {
          # See https://wiki.hyprland.org/Configuring/Variables/ for more

          rounding = 10
          blur = yes
          blur_size = 3
          blur_passes = 1
          blur_new_optimizations = on

          drop_shadow = yes
          shadow_range = 4
          shadow_render_power = 3
          col.shadow = rgba(1a1a1aee)
      }

      animations {
          enabled = yes

          # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

          bezier = myBezier, 0.05, 0.9, 0.1, 1.05

          animation = windows, 1, 7, myBezier
          animation = windowsOut, 1, 7, default, popin 80%
          animation = border, 1, 10, default
          animation = borderangle, 1, 8, default
          animation = fade, 1, 7, default
          animation = workspaces, 1, 6, default
      }

      dwindle {
          # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
          pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
          preserve_split = yes # you probably want this
      }

      master {
          # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
          new_is_master = true
      }

      gestures {
          # See https://wiki.hyprland.org/Configuring/Variables/ for more
          workspace_swipe = off
      }

      # Example per-device config
      # See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
      device:epic-mouse-v1 {
          sensitivity = -0.5
      }

      # Example windowrule v1
      # windowrule = float, ^(kitty)$
      # Example windowrule v2
      # windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
      # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


      # See https://wiki.hyprland.org/Configuring/Keywords/ for more
      $mainMod = SUPER

      # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
      bind = SUPER, Return, exec, foot
      bind = SUPER, C, killactive,
      bind = SUPER, M, exit,
      bind = SUPER, E, exec, dolphin
      bind = SUPER, V, togglefloating,
      #bind = SUPER, D, exec, wofi --show drun
      bind = SUPER, P, pseudo, # dwindle
      bind = SUPER SHIFT, J, togglesplit, # dwindle

      # Move focus with mainMod + arrow keys
      bind = SUPER, H, movefocus, l
      bind = SUPER, L, movefocus, r
      bind = SUPER, K, movefocus, u
      bind = SUPER, J, movefocus, d

      # Switch workspaces with mainMod + [0-9]
      bind = SUPER, 1, workspace, 1
      bind = SUPER, 2, workspace, 2
      bind = SUPER, 3, workspace, 3
      bind = SUPER, 4, workspace, 4
      bind = SUPER, 5, workspace, 5
      bind = SUPER, 6, workspace, 6
      bind = SUPER, 7, workspace, 7
      bind = SUPER, 8, workspace, 8
      bind = SUPER, 9, workspace, 9
      bind = SUPER, 0, workspace, 10

      # Move active window to a workspace with mainMod + SHIFT + [0-9]
      bind = SUPER SHIFT, 1, movetoworkspace, 1
      bind = SUPER SHIFT, 2, movetoworkspace, 2
      bind = SUPER SHIFT, 3, movetoworkspace, 3
      bind = SUPER SHIFT, 4, movetoworkspace, 4
      bind = SUPER SHIFT, 5, movetoworkspace, 5
      bind = SUPER SHIFT, 6, movetoworkspace, 6
      bind = SUPER SHIFT, 7, movetoworkspace, 7
      bind = SUPER SHIFT, 8, movetoworkspace, 8
      bind = SUPER SHIFT, 9, movetoworkspace, 9
      bind = SUPER SHIFT, 0, movetoworkspace, 10

      # Scroll through existing workspaces with mainMod + scroll
      bind = SUPER, mouse_down, workspace, e+1
      bind = SUPER, mouse_up, workspace, e-1

      # Move/resize windows with mainMod + LMB/RMB and dragging
      bindm = SUPER, mouse:272, movewindow
      bindm = SUPER, mouse:273, resizewindow

      # Start wofi opens wofi on first press, closes it on second
      bindr=SUPER, SUPER_L, exec, pkill wofi || wofi --show drun
    '';
  };

  programs.foot = {
    enable = true;
    settings = {
      main = {
        include = "${pkgs.foot.themes}/share/foot/themes/dracula";
        font = "Iosevka:weight=Light:size=16";
        font-bold = "Iosevka:weight=Regular:size=16";
        dpi-aware = false;
      };
      mouse = {
        hide-when-typing = true;
      };
    };
  };

  programs.mpv.enable = true;
  programs.mpv.defaultProfiles = ["gpu-hq"];
  programs.mpv.bindings = {
    WHEEL_UP = "seek 10";
    WHEEL_DOWN = "seek -10";
    "Alt+0" = "set window-scale 0.5";
  };
  programs.mpv.profiles = {
    fast = {
      vo = "vdpau";
    };
    "protocol.dvd" = {
      profile-desc = "profile for dvd:// streams";
      alang = "en";
    };
  };
  programs.mpv.scripts = [pkgs.mpvScripts.mpris];
  programs.mpv.config = {
    fullscreen = true;
    sub-auto = "fuzzy";
    #profile=gpu-hq
    #scale=ewa_lanczossharp
    #cscale=ewa_lanczossharp
    #video-sync=display-resample
    #interpolation
    #tscale=oversample
    # HDR https://github.com/mpv-player/mpv/issues/4285
    #tone-mapping=reinhard

    #####:vo=dmabuf-wayland
    #####:vo=gpu-next
    vo = "gpu-next";
    gpu-api = "vulkan";
    gpu-context = "waylandvk";
    #gpu-context=wayland
    #gpu-context=displayvk

    #hwdec=vaapi

    # https://github.com/mpv-player/mpv/issues/8981
    hdr-compute-peak = false;

    vd-lavc-dr = false;

    # If vo=gpu-next is enabled, the hdr-compute-peak=no is not needed :-?

    #audio-device=alsa/iec958:CARD=MM1,DEV=0
    #audio-device=alsa/hdmi:CARD=PCH,DEV=0
    #audio-device=alsa/iec958:CARD=X,DEV=0
  };
}
