{
  imports = [
    ./state-version.nix
    ./systemd.nix
    ./xdg.nix
    ./stylix.nix
    ./iosevka.nix
    ./virt-manager.nix
    ./hyprland.nix
    ./fuzzel.nix
    ./mako.nix
    ./foot.nix
    ./tmux.nix
    ./bash.nix
    ./fish.nix
    ./git.nix
    ./btop.nix
    ./man.nix
    ./comma.nix
    ./mdb.nix
    ./openvi.nix
    ./emacs.nix
    ./helix.nix
    ./vscode.nix
    ./texlive.nix
    ./k9s.nix
    ./ssh.nix
    ./gnupg.nix
    ./yubikey.nix
    ./gopass.nix
    ./firefox.nix
    ./chromium.nix
    ./chrome.nix
    ./imv.nix
    ./yt-dlp.nix
    ./mpv.nix
    ./obs-studio.nix
    ./games.nix
    ./misc.nix
  ];
}
