{
  imports = [
    ./state-version/hm
    ./systemd/hm
    ./xdg/hm
    ./stylix/hm
    ./iosevka/hm
    ./libvirt/hm
    ./hyprland/hm
    ./fuzzel/hm
    ./mako/hm
    ./foot/hm
    ./tmux/hm
    ./bash/hm
    ./fish/hm
    ./git/hm
    ./btop/hm
    ./man/hm
    ./comma/hm
    ./mdb/hm
    ./openvi/hm
    ./emacs/hm
    ./helix/hm
    ./vscode/hm
    ./texlive/hm
    ./k9s/hm
    ./ssh/hm
    ./gnupg/hm
    ./yubikey/hm
    ./gopass/hm
    ./firefox/hm
    ./chromium/hm
    ./chrome/hm
    ./imv/hm
    ./yt-dlp/hm
    ./mpv/hm
    ./obs-studio/hm
    ./games/hm
    ./misc/hm
  ];
}
